# syntax=docker/dockerfile:1
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="Europe/UTC"
RUN apt-get update && apt-get -y upgrade && apt-get install -y build-essential git make gcc bison flex gperf autoconf
RUN git clone --recursive https://github.com/steveicarus/iverilog.git
WORKDIR /iverilog
RUN sh autoconf.sh
RUN ./configure
RUN make
RUN make install
WORKDIR /workdir
ENTRYPOINT ["iverilog"]
